import os
import lib.consts.names as names

# TOP LEVEL CONFIG ROOT FOLDERS
CONFIG_ROOT = os.path.abspath(names.CONFIG)
STAT_CONFIG_ROOT = os.path.join(CONFIG_ROOT, names.STAT_CONFIG)
OBJ_CONFIG_ROOT = os.path.join(CONFIG_ROOT, names.OBJ_CONFIG)

# CHARACTER CONFIG FOLDERS
CHAR_CONFIG_ROOT = os.path.join(OBJ_CONFIG_ROOT, names.CHARACTER)
CHAR_JOB_CONFIG_FILE = os.path.join(CHAR_CONFIG_ROOT, names.CHAR_JOB_CONFIG_FILE)
CHAR_RACE_CONFIG_FILE = os.path.join(CHAR_CONFIG_ROOT, names.CHAR_RACE_CONFIG_FILE)

# ITEM CONFIG FOLDERS
ITEM_CONFIG_ROOT = os.path.join(OBJ_CONFIG_ROOT, names.ITEM)
CONSUMABLE_CONFIG_FILE = os.path.join(ITEM_CONFIG_ROOT, names.CONSUMABLE_CONFIG_FILE)
EQUIPMENT_CONFIG_FILE = os.path.join(ITEM_CONFIG_ROOT, names.EQUIPMENT_CONFIG_FILE)
