# SLOT NAMES
SLOT = "SLOT"
HEAD = "HEAD"
BODY = "BODY"
ARMS = "ARMS"
HANDS = "HANDS"
LEGS = "LEGS"
FEET = "FEET"

ALL_SLOTS = {
    HEAD,
    BODY,
    ARMS,
    HANDS,
    LEGS,
    FEET
}

# EMTPY SLOT NAMES
BLANK = "BLANK"
BLANK_HEAD = f"{BLANK}_{HEAD}"
BLANK_BODY = f"{BLANK}_{BODY}"
BLANK_ARMS = f"{BLANK}_{ARMS}"
BLANK_HANDS = f"{BLANK}_{HANDS}"
BLANK_LEGS = f"{BLANK}_{LEGS}"
BLANK_FEET = f"{BLANK}_{FEET}"

# CONSUMABLES
POTION = "POTION"

ALL_CONSUMABLES = {POTION}

# EQUIPMENT
HELMET = "HELMET"

ALL_EQUIPMENT = {
    BLANK_HEAD,
    BLANK_BODY,
    BLANK_ARMS,
    BLANK_HANDS,
    BLANK_LEGS,
    BLANK_FEET,
    HELMET
}
