# GENERIC NAMES
STAT = "STAT"
VAL = "VAL"
FUNC = "FUNC"
NAME = "NAME"
PARAMS = "PARAMS"

# STAT NAMES
LEVEL = "LEVEL"
HP = "HP"
ATTACK = "ATTACK"
MAGIC_ATTACK = "MAGIC_ATTACK"
DEFENSE = "DEFENSE"
MAGIC_DEFENSE = "MAGIC_DEFENSE"
SPEED = "SPEED"
EVASION = "EVASION"

# STAT AGGREGATION LIST
ALL_BASE_STATS = [
    HP, ATTACK, MAGIC_ATTACK, DEFENSE, MAGIC_DEFENSE, SPEED, EVASION
]

# STAT AGGREGATION LIST FOR LINE PRINTING
ALL_STATS = [
    [LEVEL],
    [HP],
    [ATTACK, MAGIC_ATTACK],
    [DEFENSE, MAGIC_DEFENSE],
    [SPEED, EVASION]
]
