# SCALING FUNCTION NAMES
ZERO = "ZERO"
IDENTITY = "IDENTITY"
LINEAR = "LINEAR"

# PARAMETER NAMES
M = "m"
B = "b"

# SCALING FUNCTION AGGREGATION DICTIONARY
ALL_SCALING_FUNCTIONS = {
    ZERO: {},
    IDENTITY: {},
    LINEAR: {M, B}
}
